services:
  - type: web
    name: medbuddy-api-hazel2508
    runtime: python
    rootDir: backend
    plan: free
    region: oregon
    buildCommand: pip install -r requirements_api.txt && python download_model.py
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
